version: 0.0
os: linux
file_exists_behavior: OVERWRITE
files:
  - source: /
    destination: /var/www/aws-cicd-node-server
permissions:
  - object: /var/www/aws-cicd-node-server
    pattern: "**"
    owner: ubuntu
    group: ubuntu
  - object: /var/www/aws-cicd-node-server/scripts
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ubuntu
